AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 1
Parameters:
  IAMUsername:
    Description: felix
    Type: String
Resources:
  ParameterStoreWeatherDevEncryptionKey:
    Properties:
      Description: Encryption key for secret config values for the Parameter Store
          Weather
      EnableKeyRotation: false
      Enabled: true
      KeyPolicy:
        Id: key-default-1
        Statement:
        - Action:
          - kms:Create*
          - kms:Encrypt
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Effect: Allow
          Principal:
            AWS:
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:user/${IAMUsername}
          Resource: '*'
          Sid: Allow administration of the key & encryption of new values
        - Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:DescribeKey
          Effect: Allow
          Principal:
              AWS:
              Fn::GetAtt:
              - ParameterStoreWeatherFunctionRoleDev
              - Arn
          Resource: '*'
          Sid: Allow use of the key
        Version: '2012-10-17'
    Type: AWS::KMS::Key
  ParameterStoreWeatherDevEncryptionKeyAlias:
    Properties:
      AliasName: alias/ParameterStoreWeatherKeyDev
      TargetKeyId:
        Ref: ParameterStoreWeatherDevEncryptionKey
    Type: AWS::KMS::Alias
  WeatherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: weather-processor/
      Handler: app.weatherHandler
      Role: 
        Fn:GetAtt:
        - ParameterStoreWeatherFunctionRoleDev
        - Arn
      Runtime: nodejs8.10
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          APP_CONFIG_PATH: weather-app
      Events:
        weatherProcessor:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /weather
            Method: GET
  ParameterStoreWeatherFunctionRoleDev:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ssm:GetParameter*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dev/weather-app*
          Version: '2012-10-17'
        PolicyName: ParameterStoreWeatherFunctionParameterAccess
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: ParameterStoreWeatherFunctionBasicExecution

Outputs:

    WeatherApi:
      Description: "API Gateway endpoint URL for Prod stage for weather function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weather/"

    WeatherFunction:
      Description: "Weather Lambda Function ARN"
      Value: !GetAtt WeatherFunction.Arn

    WeatherFunctionIamRole:
      Description: "Implicit IAM Role created for Weather function"
      Value: !GetAtt WeatherFunctionRole.Arn
